### PR TITLE
Fix 1.8.0

### PR DESCRIPTION
**Pull request by boricj**
See https://github.com/boricj/numworks-rpn/pull/5 for details.

### CODE REVIEW

**Comment by qguv** [comment]
Thanks for the PR. My master branch right now represents some experimental changes; I started working on 1.8.0 support and got distracted fiddling with the stack. I ought to split these changes out so we can focus on 1.8.0/master support.

As for the stack, a lot of time is wasted copying elements down the stack because the top of the stack was located at the first rather than the last element of the array. By pushing and popping at the end, we get to save all the down-the-stack copying in the case where the stack is not full. In the special case where a value is pushed to a full stack, we could easily reverse-rotate, pop the value, and push the new one.

**Comment by qguv** [comment]
Commits dc4babfc239a895fae8e9a8ab00df598717fa49b and 6e7ca693c36086caa29dcc86e1a28182612d4100 were picked onto master. Thanks again for contributing the fixes! I'm still getting some weird behavior on an almost empty stack, but I suspect it has to do with my explicit checks that operations have enough operands.

I'm heading outside to enjoy the nice Richmond weather, but I'll get to patching this back up later today or tomorrow.

**Comment by boricj** [comment]
The stack shuffling is limited to `memmove()` 16 pointers and a pair of one-level-deep `new`/`delete` Poincare nodes on each push/pull. It's not going to choke down a 96 MHz Cortex-M3 microprocessor on interactive use with a 16-level deep stack. If we end up turning this into a proper RPL-like programming environment later on then we'll need a stack implementation a bit more up to snuff.

**Comment by qguv** [comment]
Closing since those two commits are now on master. I agree that we can work more on the stack once 1.8.0 is working!

**Pull request closed without merging**
